### ISSUE TITLE
Gradle build script out of sync

### ISSUE THREAD

**Issue by alsutton** [droidcon/iosched#1]
The gradle build script is out of sync because the latest modifications have been done in an IDE which doesn't auto update the build script.

This should be fixed.

**Comment by rock3r** [comment]
I'd also add that somehow a commit by Roman Nurik, e1ae582, has been reverted. I had to manually delete the jars that were duplicating dependencies in the gradle file before being able to build the app. I can issue a pull request for this if you want.

**Comment by alsutton** [comment]
The reversion was to allow it to build outside of gradle. I've checked in a couple of changes which may fix this, if you can give them a try that'd be great.

**Comment by rock3r** [comment]
Will try ASAP!

**Comment by rock3r** [comment]
I can confirm that after merging your commits that rollback most of my tentative changes from yesterday, I can still build in Android Studio. See the pull request #5.

**Comment by alsutton** [comment]
Closing. Please open again if the re-occurs.
