### ISSUE TITLE
"Configure WiFi" action changes

### ISSUE THREAD

**Issue by veniosg** [droidcon/iosched#12]
This still uses Google I/O's network details. Should be changed to whatever network details are provided by Droidcon. 

Also, some kind of feedback once the network details have been added would be nice as it's not really clear what this action does and upon selecting it seems like it did nothing. Even a simple short-duration toast seems appropriate.

**Comment by rock3r** [comment]
I'm doing this next. I don't have network details yet, I'll have to leave a TODO on that.

**Comment by rock3r** [comment]
I can't close the issue since I don't have enough privileges for this repo, and since we still need to confirm WiFi details with the Droidcon guys. I've set a fake SSID and password for the time being.
