### ISSUE TITLE
Remove all "I/O Extended" stuff

### ISSUE THREAD

**Issue by rock3r** [droidcon/iosched#20]
There are a lot of references in the settings to the I/O Extended, livestreams, and such stuff that should be removed from the app.

I can do this, if you give me the green light, @alsutton.

**Comment by alsutton** [comment]
Go for it :)

**Comment by rock3r** [comment]
Awesome! I'm onto it

**Comment by rock3r** [comment]
I could also remove the mapping stuff as per #4 and #21. Do you plan on having maps? Or can we remove them altogether?

**Comment by alsutton** [comment]
I've no mapping plans as yet, so put a comment claiming them on the issues, and submit them as separate pull requests please :).

**Comment by rock3r** [comment]
Ok. I'll work on a new branch for this issue and another for that one, hoping that GitHub doesn't auto-merge them into #21

**Comment by rock3r** [comment]
The pull-request #25 is complete.

**Comment by rock3r** [comment]
Closed, since #25 has been merged.
