### ISSUE TITLE
Remove or change NfcBadgeActivity's behaviour

### ISSUE THREAD

**Issue by rock3r** [droidcon/iosched#23]
It's used to open the Google+ profile of attendants to the I/O, but Droidcon's badge NFC tags usually only contain the name, surname and email of the attendee. Should we switch to something like an Activity that shows the attendee details and offers to add to contacts, instead?

**Comment by alsutton** [comment]
That sounds like a good plan.

**Comment by rock3r** [comment]
Will do!
