### ISSUE TITLE
Provide sessions feedback REST endpoint

### ISSUE THREAD

**Issue by rock3r** [droidcon/iosched#26]
The sessions feedback is currently handled on sync events by the `com.funkyandroid.droidcon.uk.droidconsched.io.model.events.sessions.Feedback` class, through the com.funkyandroid.droidcon.uk.iosched.io.FeedbackHelper`.

The feedback submission URL for the PUT requests is currently resolved to `ServerRequest#DATA_ROOT + Feedback#REST_PATH` when executing the request. This ends up pointing to `http://dcuk2013.funkyandroid.net/events/droidconuk2013/sessions/{sessionId}/feedback`, which 404's.

Do we want to collect feedbacks, or do we just want to remove the feedback function altogether?

**Comment by alsutton** [comment]
For the first release we won't have feedback, so I've disabled it in https://github.com/droidcon/iosched/commit/ed8c8b0dd22f8c199a696ac7a602184dbfe81d0a
