### ISSUE TITLE
Tracks don't show up anymore in Explore

### ISSUE THREAD

**Issue by rock3r** [droidcon/iosched#31]
I can't see tracks anymore in the Explore fragment as of the head of pull request #30. I haven't touched anything regarding the tracks, their JSON, or other stuff. I noticed it after the last merge from your commits from today.

![device-2013-09-18-161619](https://f.cloud.github.com/assets/153802/1165447/fa74d846-206c-11e3-89f9-2d191230acb0.png)

The problem is most likely due to malformed JSON in respect to the `Tracks` and `Track` classes they should be deserialized into, because this manifests itself as empty `Tracks` objects being deserialized by `Gson` in `TracksHandler`:

``` java
Tracks tracksJson = new Gson().fromJson(json, Tracks.class);
if (tracksJson != null) {
    final Track[] tracks = tracksJson.getTrack();
    if (tracks != null) {
        // We never get to here: tracksJson#tracks
        // is always null!
        for (Track track : tracks) {
            parseTrack(track, batch);
        }
    }
}
```

I've tried digging into Gson to find out where the issue is, but figuring out that labyrinth is out of my scope right now. I don't have a reference JSON to work on, but by just cross-checking the `raw/tracks.json` contents and the `Track` class I can tell that there are a couple mismatches: the class is likely missing some `int[] sessions` field, and has a field that doesn't exist in the JSON, `order_in_level` (but that shouldn't be a problem).

Also, it's not clear to me at this time (because I haven't put that much into the figuring out, I guess):
- what's the difference between the `tracks.json` and `session_tracks.json` contents; intuitively the latter is the "relation table" between sessions and the tracks they belong to, through the `sessions` arrays, but then `tracks.json` has that same data. So, is `session_tracks.json` just a duplicate of a subset of `tracks.json` data?
- Why you have split the `io.*` namespaces in two places, with half the stuff in `com.funkyandroid.droidcon.uk.droidconsched.io` and half in `com.funkyandroid.droidcon.uk.iosched.io`?

**Comment by alsutton** [comment]
Have you pulled the patches since then?

**Comment by rock3r** [comment]
Yes, up to you closing issue 24

**Comment by alsutton** [comment]
Found the problem, pushed a fix. Thanks.
