### ISSUE TITLE
Prettify Tweet list items

### ISSUE THREAD

**Issue by rock3r** [droidcon/iosched#33]
I'd make the items a bit more card-like, work a bit on tipography, if possible also adding people's pictures and a few more metadata (at least the timestamp).

I could sketch something in Photoshop for feedback if you want.

**Comment by alsutton** [comment]
Go for it.

**Comment by rock3r** [comment]
Will do :)

**Comment by rock3r** [comment]
@alsutton I'm inspecting the twitter-related code. It seems like everything's is being done on the server, and the app only parses a simple JSON. Would it be possible to add a couple of fields to it? I don't have access to the server code, nor I want to duplicate the twitter implementation on the client app.

In particular, assuming you use the [search tweets](https://dev.twitter.com/docs/api/1.1/get/search/tweets) API, those are the fields I'd like to get access to from the app, in addition to the three already in the JSON:
- statuses/{status}/user/profile_image_url to show the users' profile pics
- statuses/{status}/user/verified to show the users' verified badge
- statuses/{status}/user/id to launch an "open user profile" intent
- statuses/{status}/user/screen_name to show the screen name
- statuses/{status}/retweet_count to show the retweet icon/count
- statuses/{status}/created_at to show the tweet timestamp

I'll sketch out a mockup assuming I have those items, and will move to implementation once it's confirmed.

**Comment by alsutton** [comment]
I'll add those in for you.

**Comment by rock3r** [comment]
Thanks! Please update this issue when the JSON is updated. When I have some
spare time I'll prepare the mockup, in the meantime.

**Comment by alsutton** [comment]
It should all be there now. Let me know if anything is missing.

**Comment by rock3r** [comment]
Ha! Definitely too fast for me :D

**Comment by rock3r** [comment]
Ok, I've created a mockup. If you greenlight it, @alsutton, I'll go ahead and implement it.

![Mockup](https://dl.dropboxusercontent.com/u/1419527/screens/Droidcon-UK-twitter.png)

I'll still need to work a bit on the sizing and elements weights and sizes, but the idea is pretty much this.

**Comment by alsutton** [comment]
Looks good. I'm happy for you to implement it.

**Comment by rock3r** [comment]
Will do ASAP!

**Comment by alsutton** [comment]
Is implemented; Closing.
