### ISSUE TITLE
Notifications: are they working?

### ISSUE THREAD

**Issue by rock3r** [droidcon/iosched#35]
Did the notifications get tested? Is the "starred session coming up next" notification shown by the app, given that it doesn't use GCM anymore?
Just a memo, more than anything else.

**Comment by alsutton** [comment]
The starred sessions are set up in the SessionDetailFragment, so they don't rely on GCM.

**Comment by rock3r** [comment]
Yes I know that, I meant: do we show notifications for the (locally-defined) starred sessions, since the original app used GCM and we're not?

**Comment by alsutton** [comment]
The alarms from that flow don't make use of GCM, so everything is OK.

The GCM notifications are for messages which are announcements for all attendees, which we're not using.

**Comment by rock3r** [comment]
Ok, great. Better safe than sorry, I guess.

**Comment by alsutton** [comment]
:+1:
