### ISSUE TITLE
Accents color should match logo, improve branding

### ISSUE THREAD

**Issue by rock3r** [droidcon/iosched#41]
The app could benefit from some more aggressive branding optimization.

For example, the accent colors could be set to the same green the logo uses, and probably the ActionBar logo itself could be white-on-green rather than multicolored.

Here's a quick&dirty mockup (which also includes a first draft for #34 's schedule list items UI rework):

![branded_ui](https://f.cloud.github.com/assets/153802/1210473/577e043a-25fa-11e3-8699-f12b34bf998c.png)

What do you think, @alsutton?

**Comment by alsutton** [comment]
The mini-droid was selected by the community in a competition, so it needs to stay as-is, which might make it difficult to use the green background.

**Comment by rock3r** [comment]
I see. I assumed that, since the logo is still that mini-droid, only monochrome, it could be OK. I don't know the terms of your agreement with the Droidcon guys, I'm sorry.

Still, what do you think about the other tweaks?

**Comment by alsutton** [comment]
How about posting to the G+ beta community and see what they think. I'm 50/50 about the changes, but I'm one person so lets see what the community thinks.

**Comment by rock3r** [comment]
Ok! I was also thinking about posting to the [Android Designers](https://plus.google.com/u/0/communities/113499773637471211070) community as I already did for a feedback on the Twitter stream redesign. It was actually [there](https://plus.google.com/u/0/106129364465361264599/posts/TGaCwfieoFG) I got the suggestion to use this accent color and rework the branding a bit...

**Comment by alsutton** [comment]
Have you run the design past them, if it's generally considered a good improvement then I say go for it.

**Comment by rock3r** [comment]
I'm going to post it both on the app beta community and on the Android Designers community and wait for feedback!
