### ISSUE TITLE
Session data: whole session missing from Thurs 9:45-10:25

### ISSUE THREAD

**Issue by coreform** [droidcon/iosched#47]
The 'Android Based Dongles and Wearable Accessories' session is not listed under Thurs 9:45-10:25.
It is instead listed in the 10:30-11:10 slot, however the website lineup page does not reflect that (http://uk.droidcon.com/2013/lineup/).

**Comment by alsutton** [comment]
Data corrected and should be shown on the next refresh. Thanks.
