### ISSUE TITLE
Datasets: local JSON, remote webservice

### ISSUE THREAD

**Issue by rock3r** [droidcon/iosched#6]
It seems that, as of now, no webservice exists yet to provide the data for Droidcon. The only remote endpoint working is Google's, which I guess will have to be removed pretty soon (you get both Droidcon data from the local JSONs and I/O's data from Google's webservice).

Also, the local JSON is not complete nor up-to-date. Do you have any official JSON to use, or would you need to "infer" it from the Droidcon website?

**Comment by rock3r** [comment]
This also relates to another issue: #7

**Comment by alsutton** [comment]
The JSON sync is in progess, the local data has been updated with some initial test data

**Comment by rock3r** [comment]
Great! Just a question, shouldn't we disable remote sync until there actually is a remote webservice with data? Right now it's a mess, we get both I/O's and Droidcon stuff mixed, and it's quite hard to work on it.

**Comment by alsutton** [comment]
Can you report where the IO data is still coming through, this will help identify places where we need to switch to droidcons servers or where we need to find pre-loaded data which still refers to IO

**Comment by rock3r** [comment]
The remote syncing begins at [line 156 of `SyncHelper.java`](https://github.com/rock3r/iosched/blob/DroidconUK2013/android/src/main/java/com/funkyandroid/droidcon/uk/iosched/sync/SyncHelper.java#L156-156). It seems to involve all the `com.funkyandroid.droidcon.uk.iosched.sync` and most of the  `com.funkyandroid.droidcon.uk.iosched.io` namespaces.

**Comment by alsutton** [comment]
The remote syncing has now been fixed, so anywhere that's showing IO data should be raised as an issue (one issue per place you see it). Thanks.

**Comment by alsutton** [comment]
All session, track, and speaker information now reflects what's on the droidcon UK site.
