### ISSUE TITLE
Sort sessions by room number

### ISSUE THREAD

**Issue by rock3r** [droidcon/iosched#66]
I feel like sessions should be sorted by room number when you choose amongst the sessions in a specific schedule block (you tap a block in the SessionsFragment list).

I think this makes it easier to understand where you need to go, but I'm open for debate.

**Comment by alsutton** [comment]
The current system sorts by talk name, to me this seems more logical because if you say "Talk X at 10:30" you'll be able to find it more easily than a list which is sorted by something you may not know (i.e. what room talk X is in)

**Comment by rock3r** [comment]
I understand that, and it makes sense. Never mind, it had its reasoning behind but it's far from the main use case here.
