### ISSUE TITLE
ClassCastException caused by ActionProvider

### ISSUE THREAD

**Issue by ichrisanderson** [droidcon/iosched#67]
I get the following exception on a number of devices.

The following commit looks to fix, had to use MenuItemCompat.

https://github.com/chrisanderson79/iosched/commit/00339ddf50aa8c4abff3bcde93a80944481e92a5

10-21 21:48:02.561: E/AndroidRuntime(31144): java.lang.ClassCastException: android.widget.ShareActionProvider cannot be cast to android.support.v7.internal.view.menu.MenuItemWrapperICS$ActionProviderWrapper
10-21 21:48:02.561: E/AndroidRuntime(31144):    at android.support.v7.internal.view.menu.MenuItemWrapperICS.getSupportActionProvider(MenuItemWrapperICS.java:311)
10-21 21:48:02.561: E/AndroidRuntime(31144):    at android.support.v7.internal.view.menu.MenuItemWrapperICS.checkActionProviderOverrideVisibility(MenuItemWrapperICS.java:325)
10-21 21:48:02.561: E/AndroidRuntime(31144):    at android.support.v7.internal.view.menu.MenuItemWrapperICS.setActionProvider(MenuItemWrapperICS.java:263)
10-21 21:48:02.561: E/AndroidRuntime(31144):    at com.funkyandroid.droidcon.uk.iosched.util.SessionsHelper.tryConfigureShareMenuItem(SessionsHelper.java:84)

**Comment by alsutton** [comment]
Thanks. Can you create a pull request.

**Comment by alsutton** [comment]
Pull request provided under #68 . Thanks.
