### ISSUE TITLE
Missing add to schedule button in small table portrait layout

### ISSUE THREAD

**Issue by MathieuCalba** [droidcon/iosched#69]
On the nexus 7 in portait, on the session detail screen, the add to schedule button is not shown. 
![screenshot_2013-10-24-10-11-32](https://f.cloud.github.com/assets/541565/1397349/2117be62-3c85-11e3-81bc-45712726e361.png)

**Comment by alsutton** [comment]
Fixed with https://github.com/droidcon/iosched/commit/9ee06dd0f6c72e047b4361ffda2830a623d1f695

Thanks for the report.
