### ISSUE TITLE
Lots of unused stuff still in the app

### ISSUE THREAD

**Issue by rock3r** [droidcon/iosched#7]
I can't exactly determine what is unused as of now because there is no written and shared plan yet for the app, but it seems like a lot of stuff that was used for I/O won't be used for Droidcon.

**Comment by alsutton** [comment]
Can you create issues for any individual things you notice. I think we've removed most of the unused stuff, but if you come across something then an issue for it specifically will make sure it's tracked.

**Comment by rock3r** [comment]
Yes, I've been doing it since I've opened this :)
